name = "notion-cors-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables will be set as secrets:
# Core Notion API
# wrangler secret put NOTION_TOKEN
# wrangler secret put NOTION_DATABASE_ID

# Email functionality
# wrangler secret put RESEND_API_KEY

# Admin authentication
# wrangler secret put ADMIN_TOKEN

# Enhanced GitHub integration
# wrangler secret put GITHUB_TOKEN
